[build-system]
requires = ["setuptools>=80.9", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pedantic"
version = "2.3.0"
description = "Some useful Python decorators for cleaner software development."
readme = "README.md"
requires-python = ">=3.11"
license = "Apache-2.0"
authors = [
  {name = "Willi Sontopski", email = "willi_sontopski@arcor.de"},
]
maintainers = [
  {name = "Willi Sontopski", email = "willi_sontopski@arcor.de"},
]
keywords = ["decorators", "tools", "helpers", "type-checking", "pedantic", "type annotations"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]

[project.urls]
"Bug Tracker" = "https://github.com/LostInDarkMath/pedantic-python-decorators/issues"
"Documentation" = "https://lostindarkmath.github.io/pedantic-python-decorators/pedantic/"
"Source Code" = "https://github.com/LostInDarkMath/pedantic-python-decorators"

[project.optional-dependencies]
# poetry install --extras dev
# pip install .[dev]
dev = [
  "docstring-parser==0.17",
  "Flask[async]==3.1.2",
  "multiprocess @ git+https://github.com/uqfoundation/multiprocess.git@02ea4bd36cac5013d70847815c92e1a736ef4a05",
  "Werkzeug==3.1.3",
]

[tool.setuptools.packages.find]
where = ["."]
